stages:
  - test

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'

test:check-python3-formatting:
  variables:
    FORMAT_PYTHON3_DIRECTORIES: "./"

