sudo: required

services:
  - docker

language: python
python:
  - "3.6"

before_script:
  - sudo apt-get -q update && sudo apt-get install pwgen

script:
  - ./test_docs.py 06.Administration/02.Production-installation/docs.md

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./redeploy.sh production; else ./redeploy.sh testing; fi
